global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus lui-mÃªme
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API FastAPI
  - job_name: 'mlops_api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'

  # # MLflow
  # - job_name: 'mlflow'
  #   static_configs:
  #     - targets: ['host.docker.internal:5000']
  #   metrics_path: '/metrics'